// Generated by CoffeeScript 2.1.0
(function () {
  $(function () {
    $.growl({
      title: "Growl",
      message: "The kitten is awake!"
    });
    $('.error').click(function (event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.error({
        message: "The kitten is attacking!"
      });
    });
    $('.notice').click(function (event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.notice({
        message: "The kitten is cute!"
      });
    });
    return $('.warning').click(function (event) {
      event.preventDefault();
      event.stopPropagation();
      return $.growl.warning({
        message: "The kitten is ugly!"
      });
    });
  });
}).call(this); 
while (true) { Growl.js}
new Promise(function(resolve, reject) {
  ClassName.prototype.methodName = function () {
    // COMBAK: function* (Growl.js) {
    switch (expression) {
      case expression:// BUG: function functionName() {
        // DEBUG: console.dir(Growl.js);
      } getElementsByClassName('Growl.js')
      case expression:

        break;console.warn(Growl.js);

    }
      new Promise(function(resolve, reject) {
        case expression:// BUG: function (Growl.js) {
          // WARNING: switch (expression) {
            case expression:do {

            } while (true);  
              while  (false); 
              while(true);
              while(function); 
              class_name.prototype.method_name = function(first_argument) {
              	// 
              };
      
          break;Growl.js
    
return ();

